changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
        - 'feat'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'bugfix'
        - 'fix'
    - title: '📚 Documentation'
      labels:
        - 'documentation'
        - 'docs'
    - title: '🔧 Maintenance'
      labels:
        - 'chore'
        - 'refactor'
        - 'refactoring'
        - 'maintenance'
    - title: '⚡ Performance'
      labels:
        - 'performance'
        - 'perf'
    - title: '🧪 Tests'
      labels:
        - 'test'
        - 'tests'
    - title: '🎨 UI/UX'
      labels:
        - 'ui'
        - 'ux'
        - 'design'
    - title: '🔒 Security'
      labels:
        - 'security'
    - title: '⬆️ Dependencies'
      labels:
        - 'dependencies'
        - 'deps'
    - title: '🔄 Other Changes'
      labels:
        - '*'

  exclude:
    labels:
      - 'skip-changelog'
      - 'ignore'
      - 'wontfix'
      - 'duplicate'
      - 'invalid'

  transformers:
    # Strip conventional commit prefixes if any
    - pattern: '^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?:\s*'
      target: ''

  template: |
    ## What's Changed

    $CHANGES

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$FROM_TAG...$TO_TAG

  empty_template: |
    ## What's Changed

    - Initial release

  trim_values: true
  max_pull_requests: 200
  max_back_track_time_days: 365
  sort:
    order: 'ASC'
    on_property: 'mergedAt'
